# Generated by Django 4.0.5 on 2022-06-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='kullanıcı',
        ),
    ]
