# Generated by Django 4.0.5 on 2022-06-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_user_post_kullanıcı'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='kullanıcı',
            new_name='kullanici',
        ),
    ]
